kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: k8s-cicd-rolebinding
  namespace: default
subjects:
- kind: User
  name: ci-cd-role
roleRef:
  kind: Role
  name: k8s-cicd-role
  apiGroup: rbac.authorization.k8s.io
