kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: k8s-cicd-role
  namespace: default
rules:
  - apiGroups:
      - ""
      - "apps"
      - "batch"
      - "extensions"
    resources:
      - "deployments"
      - "cronjobs"
      - "jobs"
      - "secrets"
      - "pods"
    verbs:
      - "create"
      - "describe"
      - "get"
      - "list"
      - "patch"
      - "update"
