apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ${CERTIFICATE_AUTHORITY_DATA}
    server: ${CLUSTER_ENDPOINT}
  name: arn:aws:eks:${REGION}:${AWS_ACCOUNT_ID}:cluster/${CLUSTER_NAME}
contexts:
- context:
    cluster: arn:aws:eks:${REGION}:${AWS_ACCOUNT_ID}:cluster/${CLUSTER_NAME}
    user: ci-cd
  name: arn:aws:eks:${REGION}:${AWS_ACCOUNT_ID}:cluster/${CLUSTER_NAME}
current-context: arn:aws:eks:${REGION}:${AWS_ACCOUNT_ID}:cluster/${CLUSTER_NAME}
users:
- name: ci-cd
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - ${CLUSTER_NAME}
      - -r
      - arn:aws:iam::${AWS_ACCOUNT_ID}:role/KubernetesCiCd
      command: aws-iam-authenticator
